### ISSUE TITLE
Pure lua use "type" not "typeof"

### ISSUE THREAD

**Issue by Gellipapa** [Parritz/luapacker#7]
**Describe the bug**
Hi! Currently if you want to use the builder in a plain lua file it will not work because lua has "type" for type checking not "typeof", typeof is only in luau. So we would need some logic to distinguish if it's a lua or luau file, probably based on file extension.

**To Reproduce**
1. As for the example on the main page, do it in plain lua and when you try to run it you get an error that typeof method is not recognized, because there is no such thing in lua.

**Expected behavior**
The expected result is that the build runs without errors and we get the expected result. Which currently works if I change the typeof in the bundle to type afterwards.

**Comment by Parritz** [comment]
Thanks for this! Honestly, I'm used to people using this for Roblox-related projects, so it never occurred to me that it doesn't actually work with normal Lua. I went ahead and merged #8

**Comment by Gellipapa** [comment]
> Thanks for this! Honestly, I'm used to people using this for Roblox-related projects, so it never occurred to me that it doesn't actually work with normal Lua. I went ahead and merged #8

Thanks 👍
